name: "Extract PR Diff"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  export-pr-context:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR Number
        run: |
          mkdir -p ./pr
          echo "${{ github.event.number }}" > ./pr/NR
          
      - name: Upload PR Context Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-context
          path: pr/
